services:
  - type: web
    name: jozvehyab-backend
    runtime: python
    plan: free
    buildCommand: "pip install --upgrade pip; pip install -r requirements.txt; python manage.py migrate"
    startCommand: "gunicorn mysite.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jozvehyab-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION # <-- این دستورالعمل کلیدی و نهایی است
        value: "3.11.8"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
