services:
  - type: web
    name: jozvehyab-backend
    runtime: python # <-- ما نسخه پایتون را در runtime.txt مشخص میکنیم
    plan: free
    buildCommand: "pip install -r requirements.txt; python manage.py migrate"
    startCommand: "gunicorn mysite.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jozvehyab-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
